run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - errcheck
    - gosimple
    - typecheck

issues:
  exclude-dirs:
    - stubs
    - dist
